---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: module-1
spec:
  replicas: 1
  selector:
    matchLabels:
      module: module-1
  template:
    metadata:
      labels:
        module: module-1
    spec:
      containers:
      - name: module-1-controller
        image: nginx:latest
  strategy:
    blueGreen:
      activeService: module-1-active
      previewService: module-1-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 3600
  workloadRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: ms1-rollout

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ms1-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
      - name: ms1
        image: prasad0089/ms1:2
        ports:
        - containerPort: 5000
  strategy:
    blueGreen:
      activeService: ms1-service-live
      previewService: ms1-service-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 3600

---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ms2-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
      - name: ms2
        image: prasad0089/ms2:2
        ports:
        - containerPort: 5000
  strategy:
    blueGreen:
      activeService: ms2-service-live
      previewService: ms2-service-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 3600

---
apiVersion: v1
kind: Service
metadata:
  name: module-1-active
spec:
  selector:
    module: module-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: module-1-preview
spec:
  selector:
    module: module-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ms1-service-live
spec:
  selector:
    app: ms1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: ms1-service-preview
spec:
  selector:
    app: ms1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: ms2-service-live
spec:
  selector:
    app: ms2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: ms2-service-preview
spec:
  selector:
    app: ms2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: ga-smm-ms-live.cardinality.info
    http:
      paths:
      - path: /ms1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms1-service-live
            port:
              number: 80
      - path: /ms2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms2-service-live
            port:
              number: 80
  - host: ga-smm-ms-preview.cardinality.info
    http:
      paths:
      - path: /ms1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms1-service-preview
            port:
              number: 80
      - path: /ms2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms2-service-preview
            port:
              number: 80
  tls:
  - hosts:
    - ga-smm-ms-live.cardinality.info
    - ga-smm-ms-preview.cardinality.info
    secretName: info
