---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ms1-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
      - name: ms1
        image: prasad0089/ms1:1
        ports:
        - containerPort: 5000
  strategy:
    blueGreen:
      activeService: ms1-service-live
      previewService: ms1-service-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 3600
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ms2-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
      - name: ms2
        image: prasad0089/ms2:1
        ports:
        - containerPort: 5000
  strategy:
    blueGreen:
      activeService: ms2-service-live
      previewService: ms2-service-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-service-live
spec:
  selector:
    app: ms1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-service-preview
spec:
  selector:
    app: ms1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ms2-service-live
spec:
  selector:
    app: ms2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ms2-service-preview
spec:
  selector:
    app: ms2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /live/ms1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms1-service-live
            port: 
              number: 80
      - path: /live/ms2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms2-service-live
            port: 
              number: 80
      - path: /preview/ms1(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms1-service-preview
            port: 
              number: 80
      - path: /preview/ms2(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ms2-service-preview
            port: 
              number: 80
---              
